version: "3.8"
services:
  client:
    stdin_open: true
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "17419:17419"
    volumes:
      - "/app/node_modules"
      - "./:/app"
