version: '3.8'
services:
  client:
    stdin_open: true
    restart: always
    image: morenoalexander/stockbotv2
    ports:
      - '17419:17419'
    volumes:
      - node_cache:'/app/node_modules'
volumes:
  node_cache:
