version: '3.8'
services:
  client:
    stdin_open: true
    restart: always
    image: morenoalexander/stockbotv2
    networks:
      - container-services
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - node_cache:/app/node_modules
      - container-services
    environment:
      VERSION: ${VERSION}
      DATE: ${DATE}
      DISCORD_KEY: ${DISCORD_KEY}
      FINNHUB_API_KEY: ${FINNHUB_API_KEY}
      PORT: ${PORT}
      PREFIX: ${PREFIX}
      SLACK_URL: ${SLACK_URL}
      DATABASE_URI: ${DATABASE_URI}
      APP_ID: ${APP_ID}
      MASTER_KEY: ${MASTER_KEY}
      SERVER_URL: ${SERVER_URL}
volumes:
  node_cache:
networks:
  container-services:
