# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v3.3.0
        with:
          node-version: 16

      # cache node_modules
      - name: cache node Modules
        uses: actions/cache@v3
        with:
          path: ~/node_modules
          # The cache key is used to identify the contents of the cache between runs.
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json' )}}
          restore-keys: |
            ${{ runner.os }}-npm-

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: npm install

      # run eslint
      - name: run eslint
        run: npm run eslint

      - name: Build from source -- test for compilation errors
        run: npm run build
